### ISSUE TITLE
Extremely High Spawn rates for Yeti Crabs

### ISSUE THREAD

**Issue by benbenlaw** [hybridlabs/hybrid-aquatic#85]
<img width="1015" height="316" alt="Image" src="https://github.com/user-attachments/assets/d703fcf5-13ea-4296-94ce-255f9a7fddef" />

<img width="987" height="303" alt="Image" src="https://github.com/user-attachments/assets/d95e887d-1dca-4596-a842-c236cc50501a" />

extremly high spawning causes massive tps issues. Even tried changing the add spawns in biome_modifier and that does nothing either

**Comment by MysticKoko** [comment]
Aware of this issue, being fixed in a patch shortly

**Comment by MysticKoko** [comment]
Fixed in patch 1.5.4

**Comment by VaporeonScripts** [comment]
this issue is still present in neoforge 1.21.1

<img width="666" height="590" alt="Image" src="https://github.com/user-attachments/assets/5bca5e6e-3ec5-4567-b445-e3409fae92f0" />
